"""initial schema

Revision ID: 92ad302abd39
Revises: 
Create Date: 2026-09-16 04:54:51.557400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ad302abd39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('date_range', sa.String(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('event_types', sa.JSON(), nullable=True),
    sa.Column('geographic_coverage', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('severity_reasons', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('fusion_breakdown', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('affected_area_km2', sa.Float(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('verified_report_count', sa.Integer(), nullable=True),
    sa.Column('independent_source_count', sa.Integer(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_code')
    )
    op.create_index(op.f('ix_events_city'), 'events', ['city'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_last_updated'), 'events', ['last_updated'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_state'), 'events', ['state'], unique=False)
    op.create_index(op.f('ix_events_verification_status'), 'events', ['verification_status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('trust_level', sa.String(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('verification_history_count', sa.Integer(), nullable=True),
    sa.Column('metadata_completeness_avg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmph', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('visibility_km', sa.Float(), nullable=True),
    sa.Column('baseline_rainfall_mm', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_ref_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('duplicate_status', sa.String(), nullable=True),
    sa.Column('duplicate_of_report_id', sa.Integer(), nullable=True),
    sa.Column('is_seed_data', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_city'), 'reports', ['city'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_duplicate_status'), 'reports', ['duplicate_status'], unique=False)
    op.create_index(op.f('ix_reports_event_type'), 'reports', ['event_type'], unique=False)
    op.create_index('ix_reports_event_type_timestamp_seed', 'reports', ['event_type', 'timestamp', 'is_seed_data'], unique=False)
    op.create_index(op.f('ix_reports_state'), 'reports', ['state'], unique=False)
    op.create_index(op.f('ix_reports_timestamp'), 'reports', ['timestamp'], unique=False)
    op.create_table('verification_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('admin_name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('detected_category', sa.String(), nullable=True),
    sa.Column('analysis_confidence', sa.Float(), nullable=True),
    sa.Column('evidence_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.drop_table('event_reports')
    op.drop_table('verification_actions')
    op.drop_index(op.f('ix_reports_timestamp'), table_name='reports')
    op.drop_index(op.f('ix_reports_state'), table_name='reports')
    op.drop_index('ix_reports_event_type_timestamp_seed', table_name='reports')
    op.drop_index(op.f('ix_reports_event_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_duplicate_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_city'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('alerts')
    op.drop_table('weather_observations')
    op.drop_table('sources')
    op.drop_index(op.f('ix_events_verification_status'), table_name='events')
    op.drop_index(op.f('ix_events_state'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_last_updated'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_city'), table_name='events')
    op.drop_table('events')
    op.drop_table('datasets')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
